env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  indent: ["error", 4, {
     SwitchCase: 1
  }],
  linebreak-style: ["off", "unix"],
  quotes: ["error", "single"],
  semi: ["error", "always"],
  camelcase: off,
  max-len: ["error", {
    code: 120
  }],
  no-unused-vars: off
}
